version: "3.9"

volumes:
    prometheus: ~

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus:/prometheus
    redis-exporter:
        image: bitnami/redis-exporter
        environment:
            - REDIS_ADDR=redis://redis:6379