version: "3.9"

volumes:
    loki: ~
    grafana: ~
    prometheus: ~

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    aspire-dashboard:
        image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard
        ports:
          - "4317:18889"
            - "18888:18888"