version: "3.9"

volumes:
    loki: ~
    grafana: ~
    prometheus: ~

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./config/prometheus/prometheus-collector.yml:/etc/prometheus/prometheus.yml
            - prometheus:/prometheus
        environment:
            - config.file=/etc/prometheus/prometheus-collector.yml
    redis-exporter:
        image: bitnami/redis-exporter
        environment:
            - REDIS_ADDR=redis://redis:6379
    otel-collector:
        image: otel/opentelemetry-collector-contrib:0.84.0
        command: --config /etc/otel-collector.yaml
        volumes:
            - ./config/otel-collector/otel-collector.yaml:/etc/otel-collector.yaml
        ports:
            # - "8888" # Prometheus metrics exposed by the collector for scrape
            - "8889:8889" # Prometheus exporter metrics
            - "4317:4317" # OTLP gRPC receiver
            # - "4318" # OTLP http receiver
            - "13133:13133" # health_check extension
            - "55679:55679" # zpages extension
            - "1777:1777" # performance profiler extension
        depends_on:
            - jaeger
            - prometheus
            - loki
    jaeger:
        image: jaegertracing/all-in-one
        ports:
            - "16686:16686"
            # - "14250" accept model.proto
    loki:
        image: grafana/loki
        command: -config.file=/etc/loki/local-config.yaml
        ports:
            - "3100:3100" # http
            - "9095:9095" # grpc
        volumes:
            - loki:/loki

    grafana:
        image: grafana/grafana-oss
        ports:
            - "3000:3000" # UI
        volumes:
            - grafana:/var/lib/grafana
            - ./config/grafana/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
        environment:
            - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        depends_on:
            - loki
            - prometheus