version: "3.9"

volumes:
    loki: ~
    grafana: ~
    prometheus: ~

services:
    loki:
        hostname: logs
        image: grafana/loki:latest
        command: -config.file=/etc/loki/local-config.yaml
        ports:
            - "3100:3100" # http
            - "9095:9095" # grpc
        volumes:
            - loki:/loki
    prometheus:
        hostname: metrics
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus:/prometheus
        command: # default values
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
    grafana:
        hostname: dashboard
        image: grafana/grafana-oss:latest
        ports:
            - "3000:3000" # UI
        volumes:
            - grafana:/var/lib/grafana
        environment:
            - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        depends_on:
            - loki