apiVersion: 1

datasources:
    -   name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        version: 1
        isDefault: false
        editable: false
        basicAuth: false
        jsonData:
            tlsSkipVerify: true

    -   name: Jaeger
        type: jaeger
        access: proxy
        orgId: 1
        url: http://jaeger:16686
        version: 1
        apiVersion: 1
        isDefault: false

    -   name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki:3100
        version: 1
        apiVersion: 1
        isDefault: true
        basicAuth: false
        editable: false
