receivers:
    otlp:
        protocols:
            http:
                endpoint: 0.0.0.0:4318
            grpc:
                endpoint: 0.0.0.0:4317

processors:
    batch:
        timeout: 1s

exporters:
    prometheus:
        endpoint: 0.0.0.0:8889 # accept connection to 8889 from any addresses
    jaeger:
        endpoint: jaeger:14250
        tls:
            insecure: true
    loki:
        endpoint: http://loki:3100/loki/api/v1/push

extensions:
    health_check:
    pprof:
        endpoint: :1777
    zpages:
        endpoint: :55679

service:
    extensions: [ pprof, zpages, health_check ]
    pipelines:
        metrics:
            receivers: [ otlp ]
            processors: [ batch ]
            exporters: [ prometheus ]
        traces:
            receivers: [ otlp ]
            processors: [ batch ]
            exporters: [ jaeger ]
        logs:
            receivers: [ otlp ]
            processors: [ batch ]
            exporters: [ loki ]
